"""empty message

Revision ID: 01a575cda54d
Revises: 598477dd1193
Create Date: 2020-02-04 07:39:43.504475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01a575cda54d"
down_revision = "598477dd1193"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("groups", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apps", "groups")
    # ### end Alembic commands ###
