"""empty message

Revision ID: 598477dd1193
Revises: 03663c18575b
Create Date: 2020-02-04 07:33:25.019173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598477dd1193'
down_revision = '03663c18575b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('roles', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'roles')
    # ### end Alembic commands ###
