"""empty message

Revision ID: 885c5f9b33d5
Revises: 8f5a046465e8
Create Date: 2020-02-08 13:30:01.632487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "885c5f9b33d5"
down_revision = "8f5a046465e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("tags", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apps", "tags")
    # ### end Alembic commands ###
