"""empty message

Revision ID: a36cddc6266e
Revises: ff5eb645bfe4
Create Date: 2020-02-13 10:44:25.619089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a36cddc6266e"
down_revision = "ff5eb645bfe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template_apps")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_apps",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("prefix", sa.VARCHAR(), nullable=True),
        sa.Column("url", sa.VARCHAR(), nullable=True),
        sa.Column("icon", sa.VARCHAR(), nullable=True),
        sa.Column("sidebar_icon", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("open_in", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
