"""empty message

Revision ID: ce94252d9023
Revises: a36cddc6266e
Create Date: 2020-03-08 10:56:30.470619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce94252d9023"
down_revision = "a36cddc6266e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("custom_app_title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "custom_app_title")
    # ### end Alembic commands ###
