"""empty message

Revision ID: ff5eb645bfe4
Revises: 885c5f9b33d5
Create Date: 2020-02-12 16:09:39.133644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff5eb645bfe4"
down_revision = "885c5f9b33d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("home_view_mode", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "home_view_mode")
    # ### end Alembic commands ###
